[package]
name = "distance"
version = "0.1.0"
authors = ["Marcus Brummer <mbrlabs7@gmail.com>"]

keywords = ["string matching", "string", "matching", "levenshtein"]
repository = "https://github.com/mbrlabs/distance"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
